INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Gris');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Crema');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Beige');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Canela');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Atigrado');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Tricolor');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Gris Azulado');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Oscuro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón Oscuro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rojo');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón Claro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Plateado');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Claro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Marrón');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Oscuro y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Oscuro y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Claro y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Claro y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Gris Oscuro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Azul');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Amarillo');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Chocolate');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Marrón Claro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Gris');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Gris y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Rubio');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Blanco y Marrón');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Blanco y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Plateado');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Negro y Crema');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Oscuro y Marrón Claro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Oscuro y Gris');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio Claro y Gris');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rubio y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón Oscuro y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón Claro y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Marrón Claro y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Gris Azulado y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Blanco y Crema');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Atigrado y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Atigrado y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Tricolor y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Tricolor y Negro');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Rojo y Blanco');
INSERT INTO `colors` (`id`, `name`) VALUES (NULL, 'Azul y Blanco');
