INSERT INTO `medicines` (`name`, `price`) VALUES ('Paravet Plus - Perros', 50.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('FelineCare - Gatos', 45.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('AvianGuard - Aves', 30.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('RabbitRelief - Conejos', 25.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('RodentRemedy - Roedores', 20.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('ReptiVet - Reptiles', 35.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('AquaMed - Peces', 15.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('EquineGuard - Caballos', 60.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('BovineShield - Ganado Vacuno', 70.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('OvineGuard - Ovejas', 65.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('PorcineProtector - Cerdos', 55.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('PoultryGuardian - Aves de Corral', 40.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('ExoticElixir - Animales Exóticos', 75.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('CanineCare - Perros', 48.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('FelineFortify - Gatos', 42.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('EquineEssentials - Ganado Equino', 68.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('BovineBooster - Ganado Vacuno', 75.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('AvianAid - Aves', 32.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('PoultryPurify - Aves de Corral', 38.00);
INSERT INTO `medicines` (`name`, `price`) VALUES ('ExoticElixir Plus - Animales Exóticos', 80.00);
